name: DeadEnd
author: Palkiadude
version: 1.0
api: [1.13.0]
description: A minigame where you endlessly run as the floor is dropping below you!
main: PalkiaDude\DeadEnd\Main

commands:
  tntrun:
     description: "main command"
     usage: "/tntrun"
     permission: tntrun.use
