---
Quest1Item: 296
Quest1Msg: Get Wheat!
Quest2Item: 264
Quest2Msg: Get Diamonds!
Quest3Item: 267
Quest3Msg: Get an Iron Sword
Quest4Item: 297
Quest4Msg: Get Bread!
Quest5Item: 364
Quest5Msg: Get Steak!
reward: 264
...
